trigger:
  branches:
    include:
    - refs/heads/main
  paths:
    include:
    - DscResources.psd1

variables:
- template: variables.yaml

pool:
  vmImage: windows-latest

stages:
  - stage: M365DSCPrepare
    displayName: 'Microsoft365DSC prepare'
    jobs:
    - job: PrepareDependencies
      displayName: 'Prepare dependencies for the given DSC version'
      steps:
      - checkout: self
        fetchDepth: 1
        persistCredentials: true
        path: ./s/CICD

      # Download the required version of M365DSC and its prerequisites, package that
      # into a Zip file and upload to a Blob Storage
      - task: AzurePowerShell@5
        displayName: 'Prepare and cache modules'
        inputs:
          ScriptType: 'FilePath'
          ScriptPath: './Scripts/CacheModules.ps1'
          ScriptArguments: '-PackageSourceLocation "${{ variables.packageSourceLocation }}" -PATToken "${{ variables.patToken }}" -BlobResourceGroup "${{ variables.blobResourceGroup }}" -BlobStorageAccount "${{ variables.blobStorageAccount }}" -BlobContainer "${{ variables.blobContainer }}"'
          azurePowerShellVersion: 'latestVersion'
          azureSubscription: '${{ variables.azureSubscription }}'
          errorActionPreference: 'Stop'
          FailOnStandardError: true
